### PR TITLE
README should specify the key used to sign

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by NArnott** [comment]
While I would prefer it to sign the referenced assembly using my signing key, that doesn't seem to be happening. I just tried this out, and it looks like the library provides it's own shared signing key that it signs all assemblies with.  It's not your own assembly's signing key.

The key is located here: https://github.com/dsplaisted/strongnamer/blob/master/src/StrongNamer/SharedKey.snk

And the targets file refers to it:
    
    <StrongNamer.AddStrongName
          Assemblies="@(ReferencePath)"
          CopyLocalFiles="@(ReferenceCopyLocalPaths)"
          SignedAssemblyFolder="$(IntermediateOutputPath)SignedAssemblies"
          KeyFile="$(MSBuildThisFileDirectory)SharedKey.snk">

I for one would request that the key used for signing be configurable, especially for more complicated solutions where multiple projects with multiple signing keys are in play.

**Comment by AArnott** [comment]
Thanks, @NArnott. I was only guessing at its behavior. I agree having it be configurable sounds like goodness.

**Comment by dsplaisted** [comment]
I'd suggest the following:

- First, look for a property such as `StrongNamerKeyFile`
- Then, try the property used to sign the assembly being built (I think it's `AssemblyOriginatorKeyFile`)
- If that doesn't exist, then fall back to the key file in the NuGet package

**Comment by dsplaisted** [comment]
Actually, I'm having second thoughts about defaulting to the same key used to sign the assembly being built.  Since strong naming isn't meant to be used for security or for identifying who built an assembly or anything, the key used shouldn't matter.  It's better to be consistent though, as the keys in the reference and in the resolved assembly need to match.

So I think we should stick with a default of using the key inside the package, but allow it to be overridden with an MSBuild property.

**Comment by AArnott** [comment]
Sounds reasonable. 

On a related note, have you taken precautions to avoid timing build breaks when a solution is being built in parallel and multiple projects reference the same nuget packages, such that your task may be running several times at once, all trying to sign the same assemblies?

**Comment by dsplaisted** [comment]
> On a related note, have you taken precautions to avoid timing build breaks when a solution is being built in parallel and multiple projects reference the same nuget packages, such that your task may be running several times at once, all trying to sign the same assemblies?

It doesn't sign the assemblies in place, it saves the signed versions into an intermediate directory which is specific to each project.

**Comment by AArnott** [comment]
Perfect 👌

**Pull request closed without merging**
